// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.12.4
// source: p2p.proto

package p2p

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type NodeStatus int32

const (
	NodeStatus_UNKNOWN NodeStatus = 0
	NodeStatus_ONLINE  NodeStatus = 1
	NodeStatus_BUSY    NodeStatus = 2
	NodeStatus_OFFLINE NodeStatus = 3
)

// Enum value maps for NodeStatus.
var (
	NodeStatus_name = map[int32]string{
		0: "UNKNOWN",
		1: "ONLINE",
		2: "BUSY",
		3: "OFFLINE",
	}
	NodeStatus_value = map[string]int32{
		"UNKNOWN": 0,
		"ONLINE":  1,
		"BUSY":    2,
		"OFFLINE": 3,
	}
)

func (x NodeStatus) Enum() *NodeStatus {
	p := new(NodeStatus)
	*p = x
	return p
}

func (x NodeStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (NodeStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_p2p_proto_enumTypes[0].Descriptor()
}

func (NodeStatus) Type() protoreflect.EnumType {
	return &file_p2p_proto_enumTypes[0]
}

func (x NodeStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use NodeStatus.Descriptor instead.
func (NodeStatus) EnumDescriptor() ([]byte, []int) {
	return file_p2p_proto_rawDescGZIP(), []int{0}
}

type NodeID struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Uuid          string                 `protobuf:"bytes,1,opt,name=uuid,proto3" json:"uuid,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NodeID) Reset() {
	*x = NodeID{}
	mi := &file_p2p_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NodeID) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NodeID) ProtoMessage() {}

func (x *NodeID) ProtoReflect() protoreflect.Message {
	mi := &file_p2p_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NodeID.ProtoReflect.Descriptor instead.
func (*NodeID) Descriptor() ([]byte, []int) {
	return file_p2p_proto_rawDescGZIP(), []int{0}
}

func (x *NodeID) GetUuid() string {
	if x != nil {
		return x.Uuid
	}
	return ""
}

func (x *NodeID) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type NodeAddr struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ip            string                 `protobuf:"bytes,1,opt,name=ip,proto3" json:"ip,omitempty"`
	Port          uint32                 `protobuf:"varint,2,opt,name=port,proto3" json:"port,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NodeAddr) Reset() {
	*x = NodeAddr{}
	mi := &file_p2p_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NodeAddr) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NodeAddr) ProtoMessage() {}

func (x *NodeAddr) ProtoReflect() protoreflect.Message {
	mi := &file_p2p_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NodeAddr.ProtoReflect.Descriptor instead.
func (*NodeAddr) Descriptor() ([]byte, []int) {
	return file_p2p_proto_rawDescGZIP(), []int{1}
}

func (x *NodeAddr) GetIp() string {
	if x != nil {
		return x.Ip
	}
	return ""
}

func (x *NodeAddr) GetPort() uint32 {
	if x != nil {
		return x.Port
	}
	return 0
}

// 节点完整信息 - 值对象
type NodeInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            *NodeID                `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Addrs         []*NodeAddr            `protobuf:"bytes,2,rep,name=addrs,proto3" json:"addrs,omitempty"`
	Status        NodeStatus             `protobuf:"varint,3,opt,name=status,proto3,enum=p2p.NodeStatus" json:"status,omitempty"`
	LastSeen      uint64                 `protobuf:"varint,4,opt,name=last_seen,json=lastSeen,proto3" json:"last_seen,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NodeInfo) Reset() {
	*x = NodeInfo{}
	mi := &file_p2p_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NodeInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NodeInfo) ProtoMessage() {}

func (x *NodeInfo) ProtoReflect() protoreflect.Message {
	mi := &file_p2p_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NodeInfo.ProtoReflect.Descriptor instead.
func (*NodeInfo) Descriptor() ([]byte, []int) {
	return file_p2p_proto_rawDescGZIP(), []int{2}
}

func (x *NodeInfo) GetId() *NodeID {
	if x != nil {
		return x.Id
	}
	return nil
}

func (x *NodeInfo) GetAddrs() []*NodeAddr {
	if x != nil {
		return x.Addrs
	}
	return nil
}

func (x *NodeInfo) GetStatus() NodeStatus {
	if x != nil {
		return x.Status
	}
	return NodeStatus_UNKNOWN
}

func (x *NodeInfo) GetLastSeen() uint64 {
	if x != nil {
		return x.LastSeen
	}
	return 0
}

type GetPeersReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Limit         uint32                 `protobuf:"varint,1,opt,name=limit,proto3" json:"limit,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetPeersReq) Reset() {
	*x = GetPeersReq{}
	mi := &file_p2p_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPeersReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPeersReq) ProtoMessage() {}

func (x *GetPeersReq) ProtoReflect() protoreflect.Message {
	mi := &file_p2p_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPeersReq.ProtoReflect.Descriptor instead.
func (*GetPeersReq) Descriptor() ([]byte, []int) {
	return file_p2p_proto_rawDescGZIP(), []int{3}
}

func (x *GetPeersReq) GetLimit() uint32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

type GetPeersResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Peers         []*NodeInfo            `protobuf:"bytes,1,rep,name=peers,proto3" json:"peers,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetPeersResp) Reset() {
	*x = GetPeersResp{}
	mi := &file_p2p_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPeersResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPeersResp) ProtoMessage() {}

func (x *GetPeersResp) ProtoReflect() protoreflect.Message {
	mi := &file_p2p_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPeersResp.ProtoReflect.Descriptor instead.
func (*GetPeersResp) Descriptor() ([]byte, []int) {
	return file_p2p_proto_rawDescGZIP(), []int{4}
}

func (x *GetPeersResp) GetPeers() []*NodeInfo {
	if x != nil {
		return x.Peers
	}
	return nil
}

type FindNodeReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Target        *NodeID                `protobuf:"bytes,1,opt,name=target,proto3" json:"target,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FindNodeReq) Reset() {
	*x = FindNodeReq{}
	mi := &file_p2p_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FindNodeReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FindNodeReq) ProtoMessage() {}

func (x *FindNodeReq) ProtoReflect() protoreflect.Message {
	mi := &file_p2p_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FindNodeReq.ProtoReflect.Descriptor instead.
func (*FindNodeReq) Descriptor() ([]byte, []int) {
	return file_p2p_proto_rawDescGZIP(), []int{5}
}

func (x *FindNodeReq) GetTarget() *NodeID {
	if x != nil {
		return x.Target
	}
	return nil
}

type FindNodeResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Node          *NodeInfo              `protobuf:"bytes,1,opt,name=node,proto3" json:"node,omitempty"`
	Found         bool                   `protobuf:"varint,2,opt,name=found,proto3" json:"found,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FindNodeResp) Reset() {
	*x = FindNodeResp{}
	mi := &file_p2p_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FindNodeResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FindNodeResp) ProtoMessage() {}

func (x *FindNodeResp) ProtoReflect() protoreflect.Message {
	mi := &file_p2p_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FindNodeResp.ProtoReflect.Descriptor instead.
func (*FindNodeResp) Descriptor() ([]byte, []int) {
	return file_p2p_proto_rawDescGZIP(), []int{6}
}

func (x *FindNodeResp) GetNode() *NodeInfo {
	if x != nil {
		return x.Node
	}
	return nil
}

func (x *FindNodeResp) GetFound() bool {
	if x != nil {
		return x.Found
	}
	return false
}

type HandshakeReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Self          *NodeInfo              `protobuf:"bytes,1,opt,name=self,proto3" json:"self,omitempty"`
	ProtoVersion  uint32                 `protobuf:"varint,2,opt,name=proto_version,json=protoVersion,proto3" json:"proto_version,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HandshakeReq) Reset() {
	*x = HandshakeReq{}
	mi := &file_p2p_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HandshakeReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HandshakeReq) ProtoMessage() {}

func (x *HandshakeReq) ProtoReflect() protoreflect.Message {
	mi := &file_p2p_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HandshakeReq.ProtoReflect.Descriptor instead.
func (*HandshakeReq) Descriptor() ([]byte, []int) {
	return file_p2p_proto_rawDescGZIP(), []int{7}
}

func (x *HandshakeReq) GetSelf() *NodeInfo {
	if x != nil {
		return x.Self
	}
	return nil
}

func (x *HandshakeReq) GetProtoVersion() uint32 {
	if x != nil {
		return x.ProtoVersion
	}
	return 0
}

type HandshakeResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Peer          *NodeInfo              `protobuf:"bytes,1,opt,name=peer,proto3" json:"peer,omitempty"`                               // 对方的完整信息
	KnownPeers    []*NodeInfo            `protobuf:"bytes,2,rep,name=known_peers,json=knownPeers,proto3" json:"known_peers,omitempty"` // 对方已知的其他节点（替代 NotifyNodeJoin！）
	Accepted      bool                   `protobuf:"varint,3,opt,name=accepted,proto3" json:"accepted,omitempty"`
	RejectReason  string                 `protobuf:"bytes,4,opt,name=reject_reason,json=rejectReason,proto3" json:"reject_reason,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HandshakeResp) Reset() {
	*x = HandshakeResp{}
	mi := &file_p2p_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HandshakeResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HandshakeResp) ProtoMessage() {}

func (x *HandshakeResp) ProtoReflect() protoreflect.Message {
	mi := &file_p2p_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HandshakeResp.ProtoReflect.Descriptor instead.
func (*HandshakeResp) Descriptor() ([]byte, []int) {
	return file_p2p_proto_rawDescGZIP(), []int{8}
}

func (x *HandshakeResp) GetPeer() *NodeInfo {
	if x != nil {
		return x.Peer
	}
	return nil
}

func (x *HandshakeResp) GetKnownPeers() []*NodeInfo {
	if x != nil {
		return x.KnownPeers
	}
	return nil
}

func (x *HandshakeResp) GetAccepted() bool {
	if x != nil {
		return x.Accepted
	}
	return false
}

func (x *HandshakeResp) GetRejectReason() string {
	if x != nil {
		return x.RejectReason
	}
	return ""
}

type HeartbeatReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NodeId        *NodeID                `protobuf:"bytes,1,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	Timestamp     uint64                 `protobuf:"varint,2,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HeartbeatReq) Reset() {
	*x = HeartbeatReq{}
	mi := &file_p2p_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HeartbeatReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HeartbeatReq) ProtoMessage() {}

func (x *HeartbeatReq) ProtoReflect() protoreflect.Message {
	mi := &file_p2p_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HeartbeatReq.ProtoReflect.Descriptor instead.
func (*HeartbeatReq) Descriptor() ([]byte, []int) {
	return file_p2p_proto_rawDescGZIP(), []int{9}
}

func (x *HeartbeatReq) GetNodeId() *NodeID {
	if x != nil {
		return x.NodeId
	}
	return nil
}

func (x *HeartbeatReq) GetTimestamp() uint64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

type HeartbeatResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        NodeStatus             `protobuf:"varint,1,opt,name=status,proto3,enum=p2p.NodeStatus" json:"status,omitempty"`
	Timestamp     uint64                 `protobuf:"varint,2,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HeartbeatResp) Reset() {
	*x = HeartbeatResp{}
	mi := &file_p2p_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HeartbeatResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HeartbeatResp) ProtoMessage() {}

func (x *HeartbeatResp) ProtoReflect() protoreflect.Message {
	mi := &file_p2p_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HeartbeatResp.ProtoReflect.Descriptor instead.
func (*HeartbeatResp) Descriptor() ([]byte, []int) {
	return file_p2p_proto_rawDescGZIP(), []int{10}
}

func (x *HeartbeatResp) GetStatus() NodeStatus {
	if x != nil {
		return x.Status
	}
	return NodeStatus_UNKNOWN
}

func (x *HeartbeatResp) GetTimestamp() uint64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

type DisconnectReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NodeId        *NodeID                `protobuf:"bytes,1,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	Reason        string                 `protobuf:"bytes,2,opt,name=reason,proto3" json:"reason,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DisconnectReq) Reset() {
	*x = DisconnectReq{}
	mi := &file_p2p_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DisconnectReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DisconnectReq) ProtoMessage() {}

func (x *DisconnectReq) ProtoReflect() protoreflect.Message {
	mi := &file_p2p_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DisconnectReq.ProtoReflect.Descriptor instead.
func (*DisconnectReq) Descriptor() ([]byte, []int) {
	return file_p2p_proto_rawDescGZIP(), []int{11}
}

func (x *DisconnectReq) GetNodeId() *NodeID {
	if x != nil {
		return x.NodeId
	}
	return nil
}

func (x *DisconnectReq) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

type DisconnectResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Acknowledged  bool                   `protobuf:"varint,1,opt,name=acknowledged,proto3" json:"acknowledged,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DisconnectResp) Reset() {
	*x = DisconnectResp{}
	mi := &file_p2p_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DisconnectResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DisconnectResp) ProtoMessage() {}

func (x *DisconnectResp) ProtoReflect() protoreflect.Message {
	mi := &file_p2p_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DisconnectResp.ProtoReflect.Descriptor instead.
func (*DisconnectResp) Descriptor() ([]byte, []int) {
	return file_p2p_proto_rawDescGZIP(), []int{12}
}

func (x *DisconnectResp) GetAcknowledged() bool {
	if x != nil {
		return x.Acknowledged
	}
	return false
}

type NotifyNodeJoinReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NewNode       *NodeInfo              `protobuf:"bytes,1,opt,name=new_node,json=newNode,proto3" json:"new_node,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NotifyNodeJoinReq) Reset() {
	*x = NotifyNodeJoinReq{}
	mi := &file_p2p_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NotifyNodeJoinReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NotifyNodeJoinReq) ProtoMessage() {}

func (x *NotifyNodeJoinReq) ProtoReflect() protoreflect.Message {
	mi := &file_p2p_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NotifyNodeJoinReq.ProtoReflect.Descriptor instead.
func (*NotifyNodeJoinReq) Descriptor() ([]byte, []int) {
	return file_p2p_proto_rawDescGZIP(), []int{13}
}

func (x *NotifyNodeJoinReq) GetNewNode() *NodeInfo {
	if x != nil {
		return x.NewNode
	}
	return nil
}

type NotifyNodeJoinResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Acknowledged  bool                   `protobuf:"varint,1,opt,name=acknowledged,proto3" json:"acknowledged,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NotifyNodeJoinResp) Reset() {
	*x = NotifyNodeJoinResp{}
	mi := &file_p2p_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NotifyNodeJoinResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NotifyNodeJoinResp) ProtoMessage() {}

func (x *NotifyNodeJoinResp) ProtoReflect() protoreflect.Message {
	mi := &file_p2p_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NotifyNodeJoinResp.ProtoReflect.Descriptor instead.
func (*NotifyNodeJoinResp) Descriptor() ([]byte, []int) {
	return file_p2p_proto_rawDescGZIP(), []int{14}
}

func (x *NotifyNodeJoinResp) GetAcknowledged() bool {
	if x != nil {
		return x.Acknowledged
	}
	return false
}

type Envelope struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	MsgId string                 `protobuf:"bytes,1,opt,name=msg_id,json=msgId,proto3" json:"msg_id,omitempty"`
	From  *NodeID                `protobuf:"bytes,2,opt,name=from,proto3" json:"from,omitempty"`
	// Types that are valid to be assigned to Payload:
	//
	//	*Envelope_Text
	//	*Envelope_Ping
	//	*Envelope_Pong
	Payload       isEnvelope_Payload `protobuf_oneof:"payload"`
	Timestamp     uint64             `protobuf:"varint,6,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Envelope) Reset() {
	*x = Envelope{}
	mi := &file_p2p_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Envelope) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Envelope) ProtoMessage() {}

func (x *Envelope) ProtoReflect() protoreflect.Message {
	mi := &file_p2p_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Envelope.ProtoReflect.Descriptor instead.
func (*Envelope) Descriptor() ([]byte, []int) {
	return file_p2p_proto_rawDescGZIP(), []int{15}
}

func (x *Envelope) GetMsgId() string {
	if x != nil {
		return x.MsgId
	}
	return ""
}

func (x *Envelope) GetFrom() *NodeID {
	if x != nil {
		return x.From
	}
	return nil
}

func (x *Envelope) GetPayload() isEnvelope_Payload {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *Envelope) GetText() *TextMessage {
	if x != nil {
		if x, ok := x.Payload.(*Envelope_Text); ok {
			return x.Text
		}
	}
	return nil
}

func (x *Envelope) GetPing() *Ping {
	if x != nil {
		if x, ok := x.Payload.(*Envelope_Ping); ok {
			return x.Ping
		}
	}
	return nil
}

func (x *Envelope) GetPong() *Pong {
	if x != nil {
		if x, ok := x.Payload.(*Envelope_Pong); ok {
			return x.Pong
		}
	}
	return nil
}

func (x *Envelope) GetTimestamp() uint64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

type isEnvelope_Payload interface {
	isEnvelope_Payload()
}

type Envelope_Text struct {
	Text *TextMessage `protobuf:"bytes,3,opt,name=text,proto3,oneof"`
}

type Envelope_Ping struct {
	Ping *Ping `protobuf:"bytes,5,opt,name=ping,proto3,oneof"`
}

type Envelope_Pong struct {
	Pong *Pong `protobuf:"bytes,7,opt,name=pong,proto3,oneof"`
}

func (*Envelope_Text) isEnvelope_Payload() {}

func (*Envelope_Ping) isEnvelope_Payload() {}

func (*Envelope_Pong) isEnvelope_Payload() {}

type TextMessage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Content       string                 `protobuf:"bytes,1,opt,name=content,proto3" json:"content,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TextMessage) Reset() {
	*x = TextMessage{}
	mi := &file_p2p_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TextMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TextMessage) ProtoMessage() {}

func (x *TextMessage) ProtoReflect() protoreflect.Message {
	mi := &file_p2p_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TextMessage.ProtoReflect.Descriptor instead.
func (*TextMessage) Descriptor() ([]byte, []int) {
	return file_p2p_proto_rawDescGZIP(), []int{16}
}

func (x *TextMessage) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

type Ping struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Nonce         []byte                 `protobuf:"bytes,1,opt,name=nonce,proto3" json:"nonce,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Ping) Reset() {
	*x = Ping{}
	mi := &file_p2p_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Ping) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Ping) ProtoMessage() {}

func (x *Ping) ProtoReflect() protoreflect.Message {
	mi := &file_p2p_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Ping.ProtoReflect.Descriptor instead.
func (*Ping) Descriptor() ([]byte, []int) {
	return file_p2p_proto_rawDescGZIP(), []int{17}
}

func (x *Ping) GetNonce() []byte {
	if x != nil {
		return x.Nonce
	}
	return nil
}

type Pong struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Nonce         []byte                 `protobuf:"bytes,1,opt,name=nonce,proto3" json:"nonce,omitempty"`
	PingTimestamp uint64                 `protobuf:"varint,2,opt,name=ping_timestamp,json=pingTimestamp,proto3" json:"ping_timestamp,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Pong) Reset() {
	*x = Pong{}
	mi := &file_p2p_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Pong) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Pong) ProtoMessage() {}

func (x *Pong) ProtoReflect() protoreflect.Message {
	mi := &file_p2p_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Pong.ProtoReflect.Descriptor instead.
func (*Pong) Descriptor() ([]byte, []int) {
	return file_p2p_proto_rawDescGZIP(), []int{18}
}

func (x *Pong) GetNonce() []byte {
	if x != nil {
		return x.Nonce
	}
	return nil
}

func (x *Pong) GetPingTimestamp() uint64 {
	if x != nil {
		return x.PingTimestamp
	}
	return 0
}

var File_p2p_proto protoreflect.FileDescriptor

const file_p2p_proto_rawDesc = "" +
	"\n" +
	"\tp2p.proto\x12\x03p2p\"0\n" +
	"\x06NodeID\x12\x12\n" +
	"\x04uuid\x18\x01 \x01(\tR\x04uuid\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\".\n" +
	"\bNodeAddr\x12\x0e\n" +
	"\x02ip\x18\x01 \x01(\tR\x02ip\x12\x12\n" +
	"\x04port\x18\x02 \x01(\rR\x04port\"\x92\x01\n" +
	"\bNodeInfo\x12\x1b\n" +
	"\x02id\x18\x01 \x01(\v2\v.p2p.NodeIDR\x02id\x12#\n" +
	"\x05addrs\x18\x02 \x03(\v2\r.p2p.NodeAddrR\x05addrs\x12'\n" +
	"\x06status\x18\x03 \x01(\x0e2\x0f.p2p.NodeStatusR\x06status\x12\x1b\n" +
	"\tlast_seen\x18\x04 \x01(\x04R\blastSeen\"#\n" +
	"\vGetPeersReq\x12\x14\n" +
	"\x05limit\x18\x01 \x01(\rR\x05limit\"3\n" +
	"\fGetPeersResp\x12#\n" +
	"\x05peers\x18\x01 \x03(\v2\r.p2p.NodeInfoR\x05peers\"2\n" +
	"\vFindNodeReq\x12#\n" +
	"\x06target\x18\x01 \x01(\v2\v.p2p.NodeIDR\x06target\"G\n" +
	"\fFindNodeResp\x12!\n" +
	"\x04node\x18\x01 \x01(\v2\r.p2p.NodeInfoR\x04node\x12\x14\n" +
	"\x05found\x18\x02 \x01(\bR\x05found\"V\n" +
	"\fHandshakeReq\x12!\n" +
	"\x04self\x18\x01 \x01(\v2\r.p2p.NodeInfoR\x04self\x12#\n" +
	"\rproto_version\x18\x02 \x01(\rR\fprotoVersion\"\xa3\x01\n" +
	"\rHandshakeResp\x12!\n" +
	"\x04peer\x18\x01 \x01(\v2\r.p2p.NodeInfoR\x04peer\x12.\n" +
	"\vknown_peers\x18\x02 \x03(\v2\r.p2p.NodeInfoR\n" +
	"knownPeers\x12\x1a\n" +
	"\baccepted\x18\x03 \x01(\bR\baccepted\x12#\n" +
	"\rreject_reason\x18\x04 \x01(\tR\frejectReason\"R\n" +
	"\fHeartbeatReq\x12$\n" +
	"\anode_id\x18\x01 \x01(\v2\v.p2p.NodeIDR\x06nodeId\x12\x1c\n" +
	"\ttimestamp\x18\x02 \x01(\x04R\ttimestamp\"V\n" +
	"\rHeartbeatResp\x12'\n" +
	"\x06status\x18\x01 \x01(\x0e2\x0f.p2p.NodeStatusR\x06status\x12\x1c\n" +
	"\ttimestamp\x18\x02 \x01(\x04R\ttimestamp\"M\n" +
	"\rDisconnectReq\x12$\n" +
	"\anode_id\x18\x01 \x01(\v2\v.p2p.NodeIDR\x06nodeId\x12\x16\n" +
	"\x06reason\x18\x02 \x01(\tR\x06reason\"4\n" +
	"\x0eDisconnectResp\x12\"\n" +
	"\facknowledged\x18\x01 \x01(\bR\facknowledged\"=\n" +
	"\x11NotifyNodeJoinReq\x12(\n" +
	"\bnew_node\x18\x01 \x01(\v2\r.p2p.NodeInfoR\anewNode\"8\n" +
	"\x12NotifyNodeJoinResp\x12\"\n" +
	"\facknowledged\x18\x01 \x01(\bR\facknowledged\"\xd5\x01\n" +
	"\bEnvelope\x12\x15\n" +
	"\x06msg_id\x18\x01 \x01(\tR\x05msgId\x12\x1f\n" +
	"\x04from\x18\x02 \x01(\v2\v.p2p.NodeIDR\x04from\x12&\n" +
	"\x04text\x18\x03 \x01(\v2\x10.p2p.TextMessageH\x00R\x04text\x12\x1f\n" +
	"\x04ping\x18\x05 \x01(\v2\t.p2p.PingH\x00R\x04ping\x12\x1f\n" +
	"\x04pong\x18\a \x01(\v2\t.p2p.PongH\x00R\x04pong\x12\x1c\n" +
	"\ttimestamp\x18\x06 \x01(\x04R\ttimestampB\t\n" +
	"\apayload\"'\n" +
	"\vTextMessage\x12\x18\n" +
	"\acontent\x18\x01 \x01(\tR\acontent\"\x1c\n" +
	"\x04Ping\x12\x14\n" +
	"\x05nonce\x18\x01 \x01(\fR\x05nonce\"C\n" +
	"\x04Pong\x12\x14\n" +
	"\x05nonce\x18\x01 \x01(\fR\x05nonce\x12%\n" +
	"\x0eping_timestamp\x18\x02 \x01(\x04R\rpingTimestamp*<\n" +
	"\n" +
	"NodeStatus\x12\v\n" +
	"\aUNKNOWN\x10\x00\x12\n" +
	"\n" +
	"\x06ONLINE\x10\x01\x12\b\n" +
	"\x04BUSY\x10\x02\x12\v\n" +
	"\aOFFLINE\x10\x032m\n" +
	"\tDiscovery\x12/\n" +
	"\bGetPeers\x12\x10.p2p.GetPeersReq\x1a\x11.p2p.GetPeersResp\x12/\n" +
	"\bFindNode\x12\x10.p2p.FindNodeReq\x1a\x11.p2p.FindNodeResp2\xee\x01\n" +
	"\n" +
	"Membership\x122\n" +
	"\tHandshake\x12\x11.p2p.HandshakeReq\x1a\x12.p2p.HandshakeResp\x122\n" +
	"\tHeartbeat\x12\x11.p2p.HeartbeatReq\x1a\x12.p2p.HeartbeatResp\x125\n" +
	"\n" +
	"Disconnect\x12\x12.p2p.DisconnectReq\x1a\x13.p2p.DisconnectResp\x12A\n" +
	"\x0eNotifyNodeJoin\x12\x16.p2p.NotifyNodeJoinReq\x1a\x17.p2p.NotifyNodeJoinResp27\n" +
	"\tMessaging\x12*\n" +
	"\x06Stream\x12\r.p2p.Envelope\x1a\r.p2p.Envelope(\x010\x01B\x11Z\x0f./proto/p2p/p2pb\x06proto3"

var (
	file_p2p_proto_rawDescOnce sync.Once
	file_p2p_proto_rawDescData []byte
)

func file_p2p_proto_rawDescGZIP() []byte {
	file_p2p_proto_rawDescOnce.Do(func() {
		file_p2p_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_p2p_proto_rawDesc), len(file_p2p_proto_rawDesc)))
	})
	return file_p2p_proto_rawDescData
}

var file_p2p_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_p2p_proto_msgTypes = make([]protoimpl.MessageInfo, 19)
var file_p2p_proto_goTypes = []any{
	(NodeStatus)(0),            // 0: p2p.NodeStatus
	(*NodeID)(nil),             // 1: p2p.NodeID
	(*NodeAddr)(nil),           // 2: p2p.NodeAddr
	(*NodeInfo)(nil),           // 3: p2p.NodeInfo
	(*GetPeersReq)(nil),        // 4: p2p.GetPeersReq
	(*GetPeersResp)(nil),       // 5: p2p.GetPeersResp
	(*FindNodeReq)(nil),        // 6: p2p.FindNodeReq
	(*FindNodeResp)(nil),       // 7: p2p.FindNodeResp
	(*HandshakeReq)(nil),       // 8: p2p.HandshakeReq
	(*HandshakeResp)(nil),      // 9: p2p.HandshakeResp
	(*HeartbeatReq)(nil),       // 10: p2p.HeartbeatReq
	(*HeartbeatResp)(nil),      // 11: p2p.HeartbeatResp
	(*DisconnectReq)(nil),      // 12: p2p.DisconnectReq
	(*DisconnectResp)(nil),     // 13: p2p.DisconnectResp
	(*NotifyNodeJoinReq)(nil),  // 14: p2p.NotifyNodeJoinReq
	(*NotifyNodeJoinResp)(nil), // 15: p2p.NotifyNodeJoinResp
	(*Envelope)(nil),           // 16: p2p.Envelope
	(*TextMessage)(nil),        // 17: p2p.TextMessage
	(*Ping)(nil),               // 18: p2p.Ping
	(*Pong)(nil),               // 19: p2p.Pong
}
var file_p2p_proto_depIdxs = []int32{
	1,  // 0: p2p.NodeInfo.id:type_name -> p2p.NodeID
	2,  // 1: p2p.NodeInfo.addrs:type_name -> p2p.NodeAddr
	0,  // 2: p2p.NodeInfo.status:type_name -> p2p.NodeStatus
	3,  // 3: p2p.GetPeersResp.peers:type_name -> p2p.NodeInfo
	1,  // 4: p2p.FindNodeReq.target:type_name -> p2p.NodeID
	3,  // 5: p2p.FindNodeResp.node:type_name -> p2p.NodeInfo
	3,  // 6: p2p.HandshakeReq.self:type_name -> p2p.NodeInfo
	3,  // 7: p2p.HandshakeResp.peer:type_name -> p2p.NodeInfo
	3,  // 8: p2p.HandshakeResp.known_peers:type_name -> p2p.NodeInfo
	1,  // 9: p2p.HeartbeatReq.node_id:type_name -> p2p.NodeID
	0,  // 10: p2p.HeartbeatResp.status:type_name -> p2p.NodeStatus
	1,  // 11: p2p.DisconnectReq.node_id:type_name -> p2p.NodeID
	3,  // 12: p2p.NotifyNodeJoinReq.new_node:type_name -> p2p.NodeInfo
	1,  // 13: p2p.Envelope.from:type_name -> p2p.NodeID
	17, // 14: p2p.Envelope.text:type_name -> p2p.TextMessage
	18, // 15: p2p.Envelope.ping:type_name -> p2p.Ping
	19, // 16: p2p.Envelope.pong:type_name -> p2p.Pong
	4,  // 17: p2p.Discovery.GetPeers:input_type -> p2p.GetPeersReq
	6,  // 18: p2p.Discovery.FindNode:input_type -> p2p.FindNodeReq
	8,  // 19: p2p.Membership.Handshake:input_type -> p2p.HandshakeReq
	10, // 20: p2p.Membership.Heartbeat:input_type -> p2p.HeartbeatReq
	12, // 21: p2p.Membership.Disconnect:input_type -> p2p.DisconnectReq
	14, // 22: p2p.Membership.NotifyNodeJoin:input_type -> p2p.NotifyNodeJoinReq
	16, // 23: p2p.Messaging.Stream:input_type -> p2p.Envelope
	5,  // 24: p2p.Discovery.GetPeers:output_type -> p2p.GetPeersResp
	7,  // 25: p2p.Discovery.FindNode:output_type -> p2p.FindNodeResp
	9,  // 26: p2p.Membership.Handshake:output_type -> p2p.HandshakeResp
	11, // 27: p2p.Membership.Heartbeat:output_type -> p2p.HeartbeatResp
	13, // 28: p2p.Membership.Disconnect:output_type -> p2p.DisconnectResp
	15, // 29: p2p.Membership.NotifyNodeJoin:output_type -> p2p.NotifyNodeJoinResp
	16, // 30: p2p.Messaging.Stream:output_type -> p2p.Envelope
	24, // [24:31] is the sub-list for method output_type
	17, // [17:24] is the sub-list for method input_type
	17, // [17:17] is the sub-list for extension type_name
	17, // [17:17] is the sub-list for extension extendee
	0,  // [0:17] is the sub-list for field type_name
}

func init() { file_p2p_proto_init() }
func file_p2p_proto_init() {
	if File_p2p_proto != nil {
		return
	}
	file_p2p_proto_msgTypes[15].OneofWrappers = []any{
		(*Envelope_Text)(nil),
		(*Envelope_Ping)(nil),
		(*Envelope_Pong)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_p2p_proto_rawDesc), len(file_p2p_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   19,
			NumExtensions: 0,
			NumServices:   3,
		},
		GoTypes:           file_p2p_proto_goTypes,
		DependencyIndexes: file_p2p_proto_depIdxs,
		EnumInfos:         file_p2p_proto_enumTypes,
		MessageInfos:      file_p2p_proto_msgTypes,
	}.Build()
	File_p2p_proto = out.File
	file_p2p_proto_goTypes = nil
	file_p2p_proto_depIdxs = nil
}
