// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v3.12.4
// source: proto/message.proto

package p2pmsg

import (
	context "context"
	empty "github.com/golang/protobuf/ptypes/empty"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	P2PPeerService_Join_FullMethodName              = "/p2pmsg.P2PPeerService/Join"
	P2PPeerService_NotifyNodeJoin_FullMethodName    = "/p2pmsg.P2PPeerService/NotifyNodeJoin"
	P2PPeerService_Leave_FullMethodName             = "/p2pmsg.P2PPeerService/Leave"
	P2PPeerService_SendHeartbeat_FullMethodName     = "/p2pmsg.P2PPeerService/SendHeartbeat"
	P2PPeerService_FindNode_FullMethodName          = "/p2pmsg.P2PPeerService/FindNode"
	P2PPeerService_PeerMessageStream_FullMethodName = "/p2pmsg.P2PPeerService/PeerMessageStream"
)

// P2PPeerServiceClient is the client API for P2PPeerService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// ========== 对等性Service设计（贴合P2P） ==========
// P2P对等服务：每个节点都实现这个Service，既是服务端也是客户端
type P2PPeerServiceClient interface {
	// 1. 节点加入（简单RPC，兼容中心化种子节点）
	Join(ctx context.Context, in *JoinReq, opts ...grpc.CallOption) (*JoinResp, error)
	// 👇 新增：通知其他节点有新节点上线
	NotifyNodeJoin(ctx context.Context, in *NodeInfo, opts ...grpc.CallOption) (*empty.Empty, error)
	// 节点下线
	Leave(ctx context.Context, in *NodeID, opts ...grpc.CallOption) (*empty.Empty, error)
	// 2. 发送心跳（简单RPC）
	SendHeartbeat(ctx context.Context, in *HeartbeatReq, opts ...grpc.CallOption) (*empty.Empty, error)
	// 3. 查找节点（简单RPC，DHT核心）
	FindNode(ctx context.Context, in *FindNodeReq, opts ...grpc.CallOption) (*NodeInfoResp, error)
	// 4. 对等消息流（双向流式RPC，核心！）
	// 每个节点都可以通过这个流收发所有类型的P2PMessage
	PeerMessageStream(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[P2PMessage, P2PMessage], error)
}

type p2PPeerServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewP2PPeerServiceClient(cc grpc.ClientConnInterface) P2PPeerServiceClient {
	return &p2PPeerServiceClient{cc}
}

func (c *p2PPeerServiceClient) Join(ctx context.Context, in *JoinReq, opts ...grpc.CallOption) (*JoinResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(JoinResp)
	err := c.cc.Invoke(ctx, P2PPeerService_Join_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *p2PPeerServiceClient) NotifyNodeJoin(ctx context.Context, in *NodeInfo, opts ...grpc.CallOption) (*empty.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(empty.Empty)
	err := c.cc.Invoke(ctx, P2PPeerService_NotifyNodeJoin_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *p2PPeerServiceClient) Leave(ctx context.Context, in *NodeID, opts ...grpc.CallOption) (*empty.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(empty.Empty)
	err := c.cc.Invoke(ctx, P2PPeerService_Leave_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *p2PPeerServiceClient) SendHeartbeat(ctx context.Context, in *HeartbeatReq, opts ...grpc.CallOption) (*empty.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(empty.Empty)
	err := c.cc.Invoke(ctx, P2PPeerService_SendHeartbeat_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *p2PPeerServiceClient) FindNode(ctx context.Context, in *FindNodeReq, opts ...grpc.CallOption) (*NodeInfoResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(NodeInfoResp)
	err := c.cc.Invoke(ctx, P2PPeerService_FindNode_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *p2PPeerServiceClient) PeerMessageStream(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[P2PMessage, P2PMessage], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &P2PPeerService_ServiceDesc.Streams[0], P2PPeerService_PeerMessageStream_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[P2PMessage, P2PMessage]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type P2PPeerService_PeerMessageStreamClient = grpc.BidiStreamingClient[P2PMessage, P2PMessage]

// P2PPeerServiceServer is the server API for P2PPeerService service.
// All implementations must embed UnimplementedP2PPeerServiceServer
// for forward compatibility.
//
// ========== 对等性Service设计（贴合P2P） ==========
// P2P对等服务：每个节点都实现这个Service，既是服务端也是客户端
type P2PPeerServiceServer interface {
	// 1. 节点加入（简单RPC，兼容中心化种子节点）
	Join(context.Context, *JoinReq) (*JoinResp, error)
	// 👇 新增：通知其他节点有新节点上线
	NotifyNodeJoin(context.Context, *NodeInfo) (*empty.Empty, error)
	// 节点下线
	Leave(context.Context, *NodeID) (*empty.Empty, error)
	// 2. 发送心跳（简单RPC）
	SendHeartbeat(context.Context, *HeartbeatReq) (*empty.Empty, error)
	// 3. 查找节点（简单RPC，DHT核心）
	FindNode(context.Context, *FindNodeReq) (*NodeInfoResp, error)
	// 4. 对等消息流（双向流式RPC，核心！）
	// 每个节点都可以通过这个流收发所有类型的P2PMessage
	PeerMessageStream(grpc.BidiStreamingServer[P2PMessage, P2PMessage]) error
	mustEmbedUnimplementedP2PPeerServiceServer()
}

// UnimplementedP2PPeerServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedP2PPeerServiceServer struct{}

func (UnimplementedP2PPeerServiceServer) Join(context.Context, *JoinReq) (*JoinResp, error) {
	return nil, status.Error(codes.Unimplemented, "method Join not implemented")
}
func (UnimplementedP2PPeerServiceServer) NotifyNodeJoin(context.Context, *NodeInfo) (*empty.Empty, error) {
	return nil, status.Error(codes.Unimplemented, "method NotifyNodeJoin not implemented")
}
func (UnimplementedP2PPeerServiceServer) Leave(context.Context, *NodeID) (*empty.Empty, error) {
	return nil, status.Error(codes.Unimplemented, "method Leave not implemented")
}
func (UnimplementedP2PPeerServiceServer) SendHeartbeat(context.Context, *HeartbeatReq) (*empty.Empty, error) {
	return nil, status.Error(codes.Unimplemented, "method SendHeartbeat not implemented")
}
func (UnimplementedP2PPeerServiceServer) FindNode(context.Context, *FindNodeReq) (*NodeInfoResp, error) {
	return nil, status.Error(codes.Unimplemented, "method FindNode not implemented")
}
func (UnimplementedP2PPeerServiceServer) PeerMessageStream(grpc.BidiStreamingServer[P2PMessage, P2PMessage]) error {
	return status.Error(codes.Unimplemented, "method PeerMessageStream not implemented")
}
func (UnimplementedP2PPeerServiceServer) mustEmbedUnimplementedP2PPeerServiceServer() {}
func (UnimplementedP2PPeerServiceServer) testEmbeddedByValue()                        {}

// UnsafeP2PPeerServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to P2PPeerServiceServer will
// result in compilation errors.
type UnsafeP2PPeerServiceServer interface {
	mustEmbedUnimplementedP2PPeerServiceServer()
}

func RegisterP2PPeerServiceServer(s grpc.ServiceRegistrar, srv P2PPeerServiceServer) {
	// If the following call panics, it indicates UnimplementedP2PPeerServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&P2PPeerService_ServiceDesc, srv)
}

func _P2PPeerService_Join_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(JoinReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(P2PPeerServiceServer).Join(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: P2PPeerService_Join_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(P2PPeerServiceServer).Join(ctx, req.(*JoinReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _P2PPeerService_NotifyNodeJoin_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(NodeInfo)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(P2PPeerServiceServer).NotifyNodeJoin(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: P2PPeerService_NotifyNodeJoin_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(P2PPeerServiceServer).NotifyNodeJoin(ctx, req.(*NodeInfo))
	}
	return interceptor(ctx, in, info, handler)
}

func _P2PPeerService_Leave_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(NodeID)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(P2PPeerServiceServer).Leave(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: P2PPeerService_Leave_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(P2PPeerServiceServer).Leave(ctx, req.(*NodeID))
	}
	return interceptor(ctx, in, info, handler)
}

func _P2PPeerService_SendHeartbeat_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HeartbeatReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(P2PPeerServiceServer).SendHeartbeat(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: P2PPeerService_SendHeartbeat_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(P2PPeerServiceServer).SendHeartbeat(ctx, req.(*HeartbeatReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _P2PPeerService_FindNode_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FindNodeReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(P2PPeerServiceServer).FindNode(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: P2PPeerService_FindNode_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(P2PPeerServiceServer).FindNode(ctx, req.(*FindNodeReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _P2PPeerService_PeerMessageStream_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(P2PPeerServiceServer).PeerMessageStream(&grpc.GenericServerStream[P2PMessage, P2PMessage]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type P2PPeerService_PeerMessageStreamServer = grpc.BidiStreamingServer[P2PMessage, P2PMessage]

// P2PPeerService_ServiceDesc is the grpc.ServiceDesc for P2PPeerService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var P2PPeerService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "p2pmsg.P2PPeerService",
	HandlerType: (*P2PPeerServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Join",
			Handler:    _P2PPeerService_Join_Handler,
		},
		{
			MethodName: "NotifyNodeJoin",
			Handler:    _P2PPeerService_NotifyNodeJoin_Handler,
		},
		{
			MethodName: "Leave",
			Handler:    _P2PPeerService_Leave_Handler,
		},
		{
			MethodName: "SendHeartbeat",
			Handler:    _P2PPeerService_SendHeartbeat_Handler,
		},
		{
			MethodName: "FindNode",
			Handler:    _P2PPeerService_FindNode_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "PeerMessageStream",
			Handler:       _P2PPeerService_PeerMessageStream_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "proto/message.proto",
}
