// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.12.4
// source: proto/message.proto

package p2pmsg

import (
	empty "github.com/golang/protobuf/ptypes/empty"
	timestamp "github.com/golang/protobuf/ptypes/timestamp"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// ========== 核心枚举定义（替代字符串，编译期校验） ==========
// NAT类型（P2P穿透核心）
type NatType int32

const (
	NatType_NAT_UNKNOWN            NatType = 0 // 未知
	NatType_NAT_PORT_RESTRICTED    NatType = 1 // 端口限制锥型
	NatType_NAT_ADDRESS_RESTRICTED NatType = 2 // 地址限制锥型
	NatType_NAT_FULL_CONE          NatType = 3 // 全锥型
	NatType_NAT_SYMMETRIC          NatType = 4 // 对称型（最难穿透）
	NatType_NAT_PUBLIC             NatType = 5 // 公网（无NAT）
)

// Enum value maps for NatType.
var (
	NatType_name = map[int32]string{
		0: "NAT_UNKNOWN",
		1: "NAT_PORT_RESTRICTED",
		2: "NAT_ADDRESS_RESTRICTED",
		3: "NAT_FULL_CONE",
		4: "NAT_SYMMETRIC",
		5: "NAT_PUBLIC",
	}
	NatType_value = map[string]int32{
		"NAT_UNKNOWN":            0,
		"NAT_PORT_RESTRICTED":    1,
		"NAT_ADDRESS_RESTRICTED": 2,
		"NAT_FULL_CONE":          3,
		"NAT_SYMMETRIC":          4,
		"NAT_PUBLIC":             5,
	}
)

func (x NatType) Enum() *NatType {
	p := new(NatType)
	*p = x
	return p
}

func (x NatType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (NatType) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_message_proto_enumTypes[0].Descriptor()
}

func (NatType) Type() protoreflect.EnumType {
	return &file_proto_message_proto_enumTypes[0]
}

func (x NatType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use NatType.Descriptor instead.
func (NatType) EnumDescriptor() ([]byte, []int) {
	return file_proto_message_proto_rawDescGZIP(), []int{0}
}

// 节点状态
type NodeStatus int32

const (
	NodeStatus_NODE_STATUS_UNKNOWN NodeStatus = 0
	NodeStatus_NODE_STATUS_ONLINE  NodeStatus = 1
	NodeStatus_NODE_STATUS_BUSY    NodeStatus = 2
	NodeStatus_NODE_STATUS_OFFLINE NodeStatus = 3
)

// Enum value maps for NodeStatus.
var (
	NodeStatus_name = map[int32]string{
		0: "NODE_STATUS_UNKNOWN",
		1: "NODE_STATUS_ONLINE",
		2: "NODE_STATUS_BUSY",
		3: "NODE_STATUS_OFFLINE",
	}
	NodeStatus_value = map[string]int32{
		"NODE_STATUS_UNKNOWN": 0,
		"NODE_STATUS_ONLINE":  1,
		"NODE_STATUS_BUSY":    2,
		"NODE_STATUS_OFFLINE": 3,
	}
)

func (x NodeStatus) Enum() *NodeStatus {
	p := new(NodeStatus)
	*p = x
	return p
}

func (x NodeStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (NodeStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_message_proto_enumTypes[1].Descriptor()
}

func (NodeStatus) Type() protoreflect.EnumType {
	return &file_proto_message_proto_enumTypes[1]
}

func (x NodeStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use NodeStatus.Descriptor instead.
func (NodeStatus) EnumDescriptor() ([]byte, []int) {
	return file_proto_message_proto_rawDescGZIP(), []int{1}
}

// 消息类型（覆盖P2P核心场景）
type MessageType int32

const (
	MessageType_MSG_UNKNOWN    MessageType = 0
	MessageType_MSG_TEXT       MessageType = 1 // 文本消息
	MessageType_MSG_HEARTBEAT  MessageType = 2 // 心跳
	MessageType_MSG_JOIN       MessageType = 3 // 加入网络
	MessageType_MSG_LEAVE      MessageType = 4 // 离开网络
	MessageType_MSG_FIND_NODE  MessageType = 5 // 查找节点
	MessageType_MSG_NODE_INFO  MessageType = 6 // 节点信息响应
	MessageType_MSG_FILE_PIECE MessageType = 7 // 文件分片
	MessageType_MSG_ACK        MessageType = 8 // 消息确认
	MessageType_MSG_ERROR      MessageType = 9 // 错误通知
)

// Enum value maps for MessageType.
var (
	MessageType_name = map[int32]string{
		0: "MSG_UNKNOWN",
		1: "MSG_TEXT",
		2: "MSG_HEARTBEAT",
		3: "MSG_JOIN",
		4: "MSG_LEAVE",
		5: "MSG_FIND_NODE",
		6: "MSG_NODE_INFO",
		7: "MSG_FILE_PIECE",
		8: "MSG_ACK",
		9: "MSG_ERROR",
	}
	MessageType_value = map[string]int32{
		"MSG_UNKNOWN":    0,
		"MSG_TEXT":       1,
		"MSG_HEARTBEAT":  2,
		"MSG_JOIN":       3,
		"MSG_LEAVE":      4,
		"MSG_FIND_NODE":  5,
		"MSG_NODE_INFO":  6,
		"MSG_FILE_PIECE": 7,
		"MSG_ACK":        8,
		"MSG_ERROR":      9,
	}
)

func (x MessageType) Enum() *MessageType {
	p := new(MessageType)
	*p = x
	return p
}

func (x MessageType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (MessageType) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_message_proto_enumTypes[2].Descriptor()
}

func (MessageType) Type() protoreflect.EnumType {
	return &file_proto_message_proto_enumTypes[2]
}

func (x MessageType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use MessageType.Descriptor instead.
func (MessageType) EnumDescriptor() ([]byte, []int) {
	return file_proto_message_proto_rawDescGZIP(), []int{2}
}

// 错误码（标准化机器解析）
type ErrorCode int32

const (
	ErrorCode_ERR_SUCCESS        ErrorCode = 0 // 成功
	ErrorCode_ERR_NODE_EXIST     ErrorCode = 1 // 节点已存在
	ErrorCode_ERR_NODE_NOT_FOUND ErrorCode = 2 // 节点未找到
	ErrorCode_ERR_NAT_FAILED     ErrorCode = 3 // NAT穿透失败
	ErrorCode_ERR_SIGN_INVALID   ErrorCode = 4 // 签名无效
	ErrorCode_ERR_NETWORK        ErrorCode = 5 // 网络错误
	ErrorCode_ERR_VERSION        ErrorCode = 6 // 版本不兼容
)

// Enum value maps for ErrorCode.
var (
	ErrorCode_name = map[int32]string{
		0: "ERR_SUCCESS",
		1: "ERR_NODE_EXIST",
		2: "ERR_NODE_NOT_FOUND",
		3: "ERR_NAT_FAILED",
		4: "ERR_SIGN_INVALID",
		5: "ERR_NETWORK",
		6: "ERR_VERSION",
	}
	ErrorCode_value = map[string]int32{
		"ERR_SUCCESS":        0,
		"ERR_NODE_EXIST":     1,
		"ERR_NODE_NOT_FOUND": 2,
		"ERR_NAT_FAILED":     3,
		"ERR_SIGN_INVALID":   4,
		"ERR_NETWORK":        5,
		"ERR_VERSION":        6,
	}
)

func (x ErrorCode) Enum() *ErrorCode {
	p := new(ErrorCode)
	*p = x
	return p
}

func (x ErrorCode) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ErrorCode) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_message_proto_enumTypes[3].Descriptor()
}

func (ErrorCode) Type() protoreflect.EnumType {
	return &file_proto_message_proto_enumTypes[3]
}

func (x ErrorCode) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ErrorCode.Descriptor instead.
func (ErrorCode) EnumDescriptor() ([]byte, []int) {
	return file_proto_message_proto_rawDescGZIP(), []int{3}
}

// ========== 基础通用结构 ==========
// 节点唯一标识（P2P核心）
type NodeID struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Uuid          string                 `protobuf:"bytes,1,opt,name=uuid,proto3" json:"uuid,omitempty"` // 全局唯一UUID（核心标识）
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"` // 可读名称（非唯一）
	Hash          []byte                 `protobuf:"bytes,3,opt,name=hash,proto3" json:"hash,omitempty"` // UUID的哈希值（用于DHT寻址）
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NodeID) Reset() {
	*x = NodeID{}
	mi := &file_proto_message_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NodeID) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NodeID) ProtoMessage() {}

func (x *NodeID) ProtoReflect() protoreflect.Message {
	mi := &file_proto_message_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NodeID.ProtoReflect.Descriptor instead.
func (*NodeID) Descriptor() ([]byte, []int) {
	return file_proto_message_proto_rawDescGZIP(), []int{0}
}

func (x *NodeID) GetUuid() string {
	if x != nil {
		return x.Uuid
	}
	return ""
}

func (x *NodeID) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *NodeID) GetHash() []byte {
	if x != nil {
		return x.Hash
	}
	return nil
}

// 节点网络信息（适配NAT穿透）
type NodeAddr struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ip            string                 `protobuf:"bytes,1,opt,name=ip,proto3" json:"ip,omitempty"`                                               // IP地址
	Port          uint32                 `protobuf:"varint,2,opt,name=port,proto3" json:"port,omitempty"`                                          // 端口
	NatType       NatType                `protobuf:"varint,3,opt,name=nat_type,json=natType,proto3,enum=p2pmsg.NatType" json:"nat_type,omitempty"` // NAT类型
	IsPublic      bool                   `protobuf:"varint,4,opt,name=is_public,json=isPublic,proto3" json:"is_public,omitempty"`                  // 是否公网地址
	Protocol      string                 `protobuf:"bytes,5,opt,name=protocol,proto3" json:"protocol,omitempty"`                                   // 协议类型（tcp/udp）
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NodeAddr) Reset() {
	*x = NodeAddr{}
	mi := &file_proto_message_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NodeAddr) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NodeAddr) ProtoMessage() {}

func (x *NodeAddr) ProtoReflect() protoreflect.Message {
	mi := &file_proto_message_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NodeAddr.ProtoReflect.Descriptor instead.
func (*NodeAddr) Descriptor() ([]byte, []int) {
	return file_proto_message_proto_rawDescGZIP(), []int{1}
}

func (x *NodeAddr) GetIp() string {
	if x != nil {
		return x.Ip
	}
	return ""
}

func (x *NodeAddr) GetPort() uint32 {
	if x != nil {
		return x.Port
	}
	return 0
}

func (x *NodeAddr) GetNatType() NatType {
	if x != nil {
		return x.NatType
	}
	return NatType_NAT_UNKNOWN
}

func (x *NodeAddr) GetIsPublic() bool {
	if x != nil {
		return x.IsPublic
	}
	return false
}

func (x *NodeAddr) GetProtocol() string {
	if x != nil {
		return x.Protocol
	}
	return ""
}

// 节点完整信息
type NodeInfo struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	Id                *NodeID                `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`                                                         // 唯一标识
	Addrs             []*NodeAddr            `protobuf:"bytes,2,rep,name=addrs,proto3" json:"addrs,omitempty"`                                                   // 多地址（公网+内网）
	Status            NodeStatus             `protobuf:"varint,3,opt,name=status,proto3,enum=p2pmsg.NodeStatus" json:"status,omitempty"`                         // 节点状态
	HeartbeatInterval uint64                 `protobuf:"varint,4,opt,name=heartbeat_interval,json=heartbeatInterval,proto3" json:"heartbeat_interval,omitempty"` // 心跳间隔（毫秒）
	Version           string                 `protobuf:"bytes,5,opt,name=version,proto3" json:"version,omitempty"`                                               // 节点版本（如v1.0.0）
	LastActive        *timestamp.Timestamp   `protobuf:"bytes,6,opt,name=last_active,json=lastActive,proto3" json:"last_active,omitempty"`                       // 最后活跃时间
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *NodeInfo) Reset() {
	*x = NodeInfo{}
	mi := &file_proto_message_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NodeInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NodeInfo) ProtoMessage() {}

func (x *NodeInfo) ProtoReflect() protoreflect.Message {
	mi := &file_proto_message_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NodeInfo.ProtoReflect.Descriptor instead.
func (*NodeInfo) Descriptor() ([]byte, []int) {
	return file_proto_message_proto_rawDescGZIP(), []int{2}
}

func (x *NodeInfo) GetId() *NodeID {
	if x != nil {
		return x.Id
	}
	return nil
}

func (x *NodeInfo) GetAddrs() []*NodeAddr {
	if x != nil {
		return x.Addrs
	}
	return nil
}

func (x *NodeInfo) GetStatus() NodeStatus {
	if x != nil {
		return x.Status
	}
	return NodeStatus_NODE_STATUS_UNKNOWN
}

func (x *NodeInfo) GetHeartbeatInterval() uint64 {
	if x != nil {
		return x.HeartbeatInterval
	}
	return 0
}

func (x *NodeInfo) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *NodeInfo) GetLastActive() *timestamp.Timestamp {
	if x != nil {
		return x.LastActive
	}
	return nil
}

// 通用错误响应
type ErrorResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          ErrorCode              `protobuf:"varint,1,opt,name=code,proto3,enum=p2pmsg.ErrorCode" json:"code,omitempty"` // 错误码
	Msg           string                 `protobuf:"bytes,2,opt,name=msg,proto3" json:"msg,omitempty"`                          // 可读错误信息
	Version       uint32                 `protobuf:"varint,3,opt,name=version,proto3" json:"version,omitempty"`                 // 协议版本
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ErrorResp) Reset() {
	*x = ErrorResp{}
	mi := &file_proto_message_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ErrorResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ErrorResp) ProtoMessage() {}

func (x *ErrorResp) ProtoReflect() protoreflect.Message {
	mi := &file_proto_message_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ErrorResp.ProtoReflect.Descriptor instead.
func (*ErrorResp) Descriptor() ([]byte, []int) {
	return file_proto_message_proto_rawDescGZIP(), []int{3}
}

func (x *ErrorResp) GetCode() ErrorCode {
	if x != nil {
		return x.Code
	}
	return ErrorCode_ERR_SUCCESS
}

func (x *ErrorResp) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}

func (x *ErrorResp) GetVersion() uint32 {
	if x != nil {
		return x.Version
	}
	return 0
}

// ========== P2P核心消息（基于通用结构扩展） ==========
// 节点加入请求（替代原P2PNetworkJoinReq）
type JoinReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NodeInfo      *NodeInfo              `protobuf:"bytes,1,opt,name=node_info,json=nodeInfo,proto3" json:"node_info,omitempty"`              // 节点完整信息
	ProtoVersion  uint32                 `protobuf:"varint,2,opt,name=proto_version,json=protoVersion,proto3" json:"proto_version,omitempty"` // 协议版本（兼容用）
	Signature     []byte                 `protobuf:"bytes,3,opt,name=signature,proto3" json:"signature,omitempty"`                            // 节点信息签名（防伪造）
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *JoinReq) Reset() {
	*x = JoinReq{}
	mi := &file_proto_message_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *JoinReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JoinReq) ProtoMessage() {}

func (x *JoinReq) ProtoReflect() protoreflect.Message {
	mi := &file_proto_message_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use JoinReq.ProtoReflect.Descriptor instead.
func (*JoinReq) Descriptor() ([]byte, []int) {
	return file_proto_message_proto_rawDescGZIP(), []int{4}
}

func (x *JoinReq) GetNodeInfo() *NodeInfo {
	if x != nil {
		return x.NodeInfo
	}
	return nil
}

func (x *JoinReq) GetProtoVersion() uint32 {
	if x != nil {
		return x.ProtoVersion
	}
	return 0
}

func (x *JoinReq) GetSignature() []byte {
	if x != nil {
		return x.Signature
	}
	return nil
}

// 节点加入响应（替代原P2PNetworkJoinRepl）
type JoinResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`                               // 是否成功
	Error         *ErrorResp             `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`                                    // 错误信息（失败时非空）
	Peers         []*NodeInfo            `protobuf:"bytes,3,rep,name=peers,proto3" json:"peers,omitempty"`                                    // 在线节点列表
	ProtoVersion  uint32                 `protobuf:"varint,4,opt,name=proto_version,json=protoVersion,proto3" json:"proto_version,omitempty"` // 服务端协议版本
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *JoinResp) Reset() {
	*x = JoinResp{}
	mi := &file_proto_message_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *JoinResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JoinResp) ProtoMessage() {}

func (x *JoinResp) ProtoReflect() protoreflect.Message {
	mi := &file_proto_message_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use JoinResp.ProtoReflect.Descriptor instead.
func (*JoinResp) Descriptor() ([]byte, []int) {
	return file_proto_message_proto_rawDescGZIP(), []int{5}
}

func (x *JoinResp) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *JoinResp) GetError() *ErrorResp {
	if x != nil {
		return x.Error
	}
	return nil
}

func (x *JoinResp) GetPeers() []*NodeInfo {
	if x != nil {
		return x.Peers
	}
	return nil
}

func (x *JoinResp) GetProtoVersion() uint32 {
	if x != nil {
		return x.ProtoVersion
	}
	return 0
}

// 心跳请求（替代原P2PNetworkHeartBeat）
type HeartbeatReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NodeId        *NodeID                `protobuf:"bytes,1,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`           // 节点ID
	Status        NodeStatus             `protobuf:"varint,2,opt,name=status,proto3,enum=p2pmsg.NodeStatus" json:"status,omitempty"` // 节点状态
	Timestamp     uint64                 `protobuf:"varint,3,opt,name=timestamp,proto3" json:"timestamp,omitempty"`                  // 时间戳（毫秒）
	Signature     []byte                 `protobuf:"bytes,4,opt,name=signature,proto3" json:"signature,omitempty"`                   // 心跳签名
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HeartbeatReq) Reset() {
	*x = HeartbeatReq{}
	mi := &file_proto_message_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HeartbeatReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HeartbeatReq) ProtoMessage() {}

func (x *HeartbeatReq) ProtoReflect() protoreflect.Message {
	mi := &file_proto_message_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HeartbeatReq.ProtoReflect.Descriptor instead.
func (*HeartbeatReq) Descriptor() ([]byte, []int) {
	return file_proto_message_proto_rawDescGZIP(), []int{6}
}

func (x *HeartbeatReq) GetNodeId() *NodeID {
	if x != nil {
		return x.NodeId
	}
	return nil
}

func (x *HeartbeatReq) GetStatus() NodeStatus {
	if x != nil {
		return x.Status
	}
	return NodeStatus_NODE_STATUS_UNKNOWN
}

func (x *HeartbeatReq) GetTimestamp() uint64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

func (x *HeartbeatReq) GetSignature() []byte {
	if x != nil {
		return x.Signature
	}
	return nil
}

// 通用消息（替代原P2PMessage）
type P2PMessage struct {
	state        protoimpl.MessageState `protogen:"open.v1"`
	MsgId        string                 `protobuf:"bytes,1,opt,name=msg_id,json=msgId,proto3" json:"msg_id,omitempty"`                       // 消息唯一ID（去重/ACK）
	Type         MessageType            `protobuf:"varint,2,opt,name=type,proto3,enum=p2pmsg.MessageType" json:"type,omitempty"`             // 消息类型（枚举）
	From         *NodeID                `protobuf:"bytes,3,opt,name=from,proto3" json:"from,omitempty"`                                      // 发送节点
	ProtoVersion uint32                 `protobuf:"varint,4,opt,name=proto_version,json=protoVersion,proto3" json:"proto_version,omitempty"` // 协议版本
	SendTime     *timestamp.Timestamp   `protobuf:"bytes,5,opt,name=send_time,json=sendTime,proto3" json:"send_time,omitempty"`              // 发送时间
	// 消息内容（按类型区分）
	//
	// Types that are valid to be assigned to Content:
	//
	//	*P2PMessage_Text
	//	*P2PMessage_Heartbeat
	//	*P2PMessage_FindNode
	//	*P2PMessage_NodeInfo
	//	*P2PMessage_FilePiece
	//	*P2PMessage_Ack
	//	*P2PMessage_Error
	Content       isP2PMessage_Content `protobuf_oneof:"content"`
	ContentHash   []byte               `protobuf:"bytes,13,opt,name=content_hash,json=contentHash,proto3" json:"content_hash,omitempty"` // 内容哈希（防篡改）
	Signature     []byte               `protobuf:"bytes,14,opt,name=signature,proto3" json:"signature,omitempty"`                        // 消息签名（验真）
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *P2PMessage) Reset() {
	*x = P2PMessage{}
	mi := &file_proto_message_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *P2PMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*P2PMessage) ProtoMessage() {}

func (x *P2PMessage) ProtoReflect() protoreflect.Message {
	mi := &file_proto_message_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use P2PMessage.ProtoReflect.Descriptor instead.
func (*P2PMessage) Descriptor() ([]byte, []int) {
	return file_proto_message_proto_rawDescGZIP(), []int{7}
}

func (x *P2PMessage) GetMsgId() string {
	if x != nil {
		return x.MsgId
	}
	return ""
}

func (x *P2PMessage) GetType() MessageType {
	if x != nil {
		return x.Type
	}
	return MessageType_MSG_UNKNOWN
}

func (x *P2PMessage) GetFrom() *NodeID {
	if x != nil {
		return x.From
	}
	return nil
}

func (x *P2PMessage) GetProtoVersion() uint32 {
	if x != nil {
		return x.ProtoVersion
	}
	return 0
}

func (x *P2PMessage) GetSendTime() *timestamp.Timestamp {
	if x != nil {
		return x.SendTime
	}
	return nil
}

func (x *P2PMessage) GetContent() isP2PMessage_Content {
	if x != nil {
		return x.Content
	}
	return nil
}

func (x *P2PMessage) GetText() string {
	if x != nil {
		if x, ok := x.Content.(*P2PMessage_Text); ok {
			return x.Text
		}
	}
	return ""
}

func (x *P2PMessage) GetHeartbeat() *HeartbeatReq {
	if x != nil {
		if x, ok := x.Content.(*P2PMessage_Heartbeat); ok {
			return x.Heartbeat
		}
	}
	return nil
}

func (x *P2PMessage) GetFindNode() *FindNodeReq {
	if x != nil {
		if x, ok := x.Content.(*P2PMessage_FindNode); ok {
			return x.FindNode
		}
	}
	return nil
}

func (x *P2PMessage) GetNodeInfo() *NodeInfoResp {
	if x != nil {
		if x, ok := x.Content.(*P2PMessage_NodeInfo); ok {
			return x.NodeInfo
		}
	}
	return nil
}

func (x *P2PMessage) GetFilePiece() *FilePiece {
	if x != nil {
		if x, ok := x.Content.(*P2PMessage_FilePiece); ok {
			return x.FilePiece
		}
	}
	return nil
}

func (x *P2PMessage) GetAck() *ACKReq {
	if x != nil {
		if x, ok := x.Content.(*P2PMessage_Ack); ok {
			return x.Ack
		}
	}
	return nil
}

func (x *P2PMessage) GetError() *ErrorResp {
	if x != nil {
		if x, ok := x.Content.(*P2PMessage_Error); ok {
			return x.Error
		}
	}
	return nil
}

func (x *P2PMessage) GetContentHash() []byte {
	if x != nil {
		return x.ContentHash
	}
	return nil
}

func (x *P2PMessage) GetSignature() []byte {
	if x != nil {
		return x.Signature
	}
	return nil
}

type isP2PMessage_Content interface {
	isP2PMessage_Content()
}

type P2PMessage_Text struct {
	Text string `protobuf:"bytes,6,opt,name=text,proto3,oneof"` // 文本内容（MSG_TEXT）
}

type P2PMessage_Heartbeat struct {
	Heartbeat *HeartbeatReq `protobuf:"bytes,7,opt,name=heartbeat,proto3,oneof"` // 心跳内容（MSG_HEARTBEAT）
}

type P2PMessage_FindNode struct {
	FindNode *FindNodeReq `protobuf:"bytes,8,opt,name=find_node,json=findNode,proto3,oneof"` // 查找节点（MSG_FIND_NODE）
}

type P2PMessage_NodeInfo struct {
	NodeInfo *NodeInfoResp `protobuf:"bytes,9,opt,name=node_info,json=nodeInfo,proto3,oneof"` // 节点信息（MSG_NODE_INFO）
}

type P2PMessage_FilePiece struct {
	FilePiece *FilePiece `protobuf:"bytes,10,opt,name=file_piece,json=filePiece,proto3,oneof"` // 文件分片（MSG_FILE_PIECE）
}

type P2PMessage_Ack struct {
	Ack *ACKReq `protobuf:"bytes,11,opt,name=ack,proto3,oneof"` // 消息确认（MSG_ACK）
}

type P2PMessage_Error struct {
	Error *ErrorResp `protobuf:"bytes,12,opt,name=error,proto3,oneof"` // 错误信息（MSG_ERROR）
}

func (*P2PMessage_Text) isP2PMessage_Content() {}

func (*P2PMessage_Heartbeat) isP2PMessage_Content() {}

func (*P2PMessage_FindNode) isP2PMessage_Content() {}

func (*P2PMessage_NodeInfo) isP2PMessage_Content() {}

func (*P2PMessage_FilePiece) isP2PMessage_Content() {}

func (*P2PMessage_Ack) isP2PMessage_Content() {}

func (*P2PMessage_Error) isP2PMessage_Content() {}

// 查找节点请求
type FindNodeReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TargetNode    *NodeID                `protobuf:"bytes,1,opt,name=target_node,json=targetNode,proto3" json:"target_node,omitempty"` // 目标节点ID
	Limit         uint32                 `protobuf:"varint,2,opt,name=limit,proto3" json:"limit,omitempty"`                            // 返回节点数量限制
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FindNodeReq) Reset() {
	*x = FindNodeReq{}
	mi := &file_proto_message_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FindNodeReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FindNodeReq) ProtoMessage() {}

func (x *FindNodeReq) ProtoReflect() protoreflect.Message {
	mi := &file_proto_message_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FindNodeReq.ProtoReflect.Descriptor instead.
func (*FindNodeReq) Descriptor() ([]byte, []int) {
	return file_proto_message_proto_rawDescGZIP(), []int{8}
}

func (x *FindNodeReq) GetTargetNode() *NodeID {
	if x != nil {
		return x.TargetNode
	}
	return nil
}

func (x *FindNodeReq) GetLimit() uint32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

// 节点信息响应
type NodeInfoResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Nodes         []*NodeInfo            `protobuf:"bytes,1,rep,name=nodes,proto3" json:"nodes,omitempty"` // 匹配的节点列表
	Error         *ErrorResp             `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"` // 错误信息
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NodeInfoResp) Reset() {
	*x = NodeInfoResp{}
	mi := &file_proto_message_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NodeInfoResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NodeInfoResp) ProtoMessage() {}

func (x *NodeInfoResp) ProtoReflect() protoreflect.Message {
	mi := &file_proto_message_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NodeInfoResp.ProtoReflect.Descriptor instead.
func (*NodeInfoResp) Descriptor() ([]byte, []int) {
	return file_proto_message_proto_rawDescGZIP(), []int{9}
}

func (x *NodeInfoResp) GetNodes() []*NodeInfo {
	if x != nil {
		return x.Nodes
	}
	return nil
}

func (x *NodeInfoResp) GetError() *ErrorResp {
	if x != nil {
		return x.Error
	}
	return nil
}

// 文件分片传输（P2P文件共享核心）
type FilePiece struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	FileId        string                 `protobuf:"bytes,1,opt,name=file_id,json=fileId,proto3" json:"file_id,omitempty"`                 // 文件唯一ID
	PieceIndex    uint32                 `protobuf:"varint,2,opt,name=piece_index,json=pieceIndex,proto3" json:"piece_index,omitempty"`    // 分片索引（从0开始）
	TotalPieces   uint32                 `protobuf:"varint,3,opt,name=total_pieces,json=totalPieces,proto3" json:"total_pieces,omitempty"` // 总分片数
	Data          []byte                 `protobuf:"bytes,4,opt,name=data,proto3" json:"data,omitempty"`                                   // 分片数据
	PieceHash     []byte                 `protobuf:"bytes,5,opt,name=piece_hash,json=pieceHash,proto3" json:"piece_hash,omitempty"`        // 分片哈希（校验）
	IsLast        bool                   `protobuf:"varint,6,opt,name=is_last,json=isLast,proto3" json:"is_last,omitempty"`                // 是否最后一个分片
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FilePiece) Reset() {
	*x = FilePiece{}
	mi := &file_proto_message_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FilePiece) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FilePiece) ProtoMessage() {}

func (x *FilePiece) ProtoReflect() protoreflect.Message {
	mi := &file_proto_message_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FilePiece.ProtoReflect.Descriptor instead.
func (*FilePiece) Descriptor() ([]byte, []int) {
	return file_proto_message_proto_rawDescGZIP(), []int{10}
}

func (x *FilePiece) GetFileId() string {
	if x != nil {
		return x.FileId
	}
	return ""
}

func (x *FilePiece) GetPieceIndex() uint32 {
	if x != nil {
		return x.PieceIndex
	}
	return 0
}

func (x *FilePiece) GetTotalPieces() uint32 {
	if x != nil {
		return x.TotalPieces
	}
	return 0
}

func (x *FilePiece) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *FilePiece) GetPieceHash() []byte {
	if x != nil {
		return x.PieceHash
	}
	return nil
}

func (x *FilePiece) GetIsLast() bool {
	if x != nil {
		return x.IsLast
	}
	return false
}

// 消息确认（可靠性核心）
type ACKReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MsgId         string                 `protobuf:"bytes,1,opt,name=msg_id,json=msgId,proto3" json:"msg_id,omitempty"` // 被确认的消息ID
	Success       bool                   `protobuf:"varint,2,opt,name=success,proto3" json:"success,omitempty"`         // 是否接收成功
	Error         *ErrorResp             `protobuf:"bytes,3,opt,name=error,proto3" json:"error,omitempty"`              // 失败原因
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ACKReq) Reset() {
	*x = ACKReq{}
	mi := &file_proto_message_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ACKReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ACKReq) ProtoMessage() {}

func (x *ACKReq) ProtoReflect() protoreflect.Message {
	mi := &file_proto_message_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ACKReq.ProtoReflect.Descriptor instead.
func (*ACKReq) Descriptor() ([]byte, []int) {
	return file_proto_message_proto_rawDescGZIP(), []int{11}
}

func (x *ACKReq) GetMsgId() string {
	if x != nil {
		return x.MsgId
	}
	return ""
}

func (x *ACKReq) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *ACKReq) GetError() *ErrorResp {
	if x != nil {
		return x.Error
	}
	return nil
}

var File_proto_message_proto protoreflect.FileDescriptor

const file_proto_message_proto_rawDesc = "" +
	"\n" +
	"\x13proto/message.proto\x12\x06p2pmsg\x1a\x1bgoogle/protobuf/empty.proto\x1a\x1fgoogle/protobuf/timestamp.proto\"D\n" +
	"\x06NodeID\x12\x12\n" +
	"\x04uuid\x18\x01 \x01(\tR\x04uuid\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x12\n" +
	"\x04hash\x18\x03 \x01(\fR\x04hash\"\x93\x01\n" +
	"\bNodeAddr\x12\x0e\n" +
	"\x02ip\x18\x01 \x01(\tR\x02ip\x12\x12\n" +
	"\x04port\x18\x02 \x01(\rR\x04port\x12*\n" +
	"\bnat_type\x18\x03 \x01(\x0e2\x0f.p2pmsg.NatTypeR\anatType\x12\x1b\n" +
	"\tis_public\x18\x04 \x01(\bR\bisPublic\x12\x1a\n" +
	"\bprotocol\x18\x05 \x01(\tR\bprotocol\"\x84\x02\n" +
	"\bNodeInfo\x12\x1e\n" +
	"\x02id\x18\x01 \x01(\v2\x0e.p2pmsg.NodeIDR\x02id\x12&\n" +
	"\x05addrs\x18\x02 \x03(\v2\x10.p2pmsg.NodeAddrR\x05addrs\x12*\n" +
	"\x06status\x18\x03 \x01(\x0e2\x12.p2pmsg.NodeStatusR\x06status\x12-\n" +
	"\x12heartbeat_interval\x18\x04 \x01(\x04R\x11heartbeatInterval\x12\x18\n" +
	"\aversion\x18\x05 \x01(\tR\aversion\x12;\n" +
	"\vlast_active\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampR\n" +
	"lastActive\"^\n" +
	"\tErrorResp\x12%\n" +
	"\x04code\x18\x01 \x01(\x0e2\x11.p2pmsg.ErrorCodeR\x04code\x12\x10\n" +
	"\x03msg\x18\x02 \x01(\tR\x03msg\x12\x18\n" +
	"\aversion\x18\x03 \x01(\rR\aversion\"{\n" +
	"\aJoinReq\x12-\n" +
	"\tnode_info\x18\x01 \x01(\v2\x10.p2pmsg.NodeInfoR\bnodeInfo\x12#\n" +
	"\rproto_version\x18\x02 \x01(\rR\fprotoVersion\x12\x1c\n" +
	"\tsignature\x18\x03 \x01(\fR\tsignature\"\x9a\x01\n" +
	"\bJoinResp\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12'\n" +
	"\x05error\x18\x02 \x01(\v2\x11.p2pmsg.ErrorRespR\x05error\x12&\n" +
	"\x05peers\x18\x03 \x03(\v2\x10.p2pmsg.NodeInfoR\x05peers\x12#\n" +
	"\rproto_version\x18\x04 \x01(\rR\fprotoVersion\"\x9f\x01\n" +
	"\fHeartbeatReq\x12'\n" +
	"\anode_id\x18\x01 \x01(\v2\x0e.p2pmsg.NodeIDR\x06nodeId\x12*\n" +
	"\x06status\x18\x02 \x01(\x0e2\x12.p2pmsg.NodeStatusR\x06status\x12\x1c\n" +
	"\ttimestamp\x18\x03 \x01(\x04R\ttimestamp\x12\x1c\n" +
	"\tsignature\x18\x04 \x01(\fR\tsignature\"\xd8\x04\n" +
	"\n" +
	"P2PMessage\x12\x15\n" +
	"\x06msg_id\x18\x01 \x01(\tR\x05msgId\x12'\n" +
	"\x04type\x18\x02 \x01(\x0e2\x13.p2pmsg.MessageTypeR\x04type\x12\"\n" +
	"\x04from\x18\x03 \x01(\v2\x0e.p2pmsg.NodeIDR\x04from\x12#\n" +
	"\rproto_version\x18\x04 \x01(\rR\fprotoVersion\x127\n" +
	"\tsend_time\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\bsendTime\x12\x14\n" +
	"\x04text\x18\x06 \x01(\tH\x00R\x04text\x124\n" +
	"\theartbeat\x18\a \x01(\v2\x14.p2pmsg.HeartbeatReqH\x00R\theartbeat\x122\n" +
	"\tfind_node\x18\b \x01(\v2\x13.p2pmsg.FindNodeReqH\x00R\bfindNode\x123\n" +
	"\tnode_info\x18\t \x01(\v2\x14.p2pmsg.NodeInfoRespH\x00R\bnodeInfo\x122\n" +
	"\n" +
	"file_piece\x18\n" +
	" \x01(\v2\x11.p2pmsg.FilePieceH\x00R\tfilePiece\x12\"\n" +
	"\x03ack\x18\v \x01(\v2\x0e.p2pmsg.ACKReqH\x00R\x03ack\x12)\n" +
	"\x05error\x18\f \x01(\v2\x11.p2pmsg.ErrorRespH\x00R\x05error\x12!\n" +
	"\fcontent_hash\x18\r \x01(\fR\vcontentHash\x12\x1c\n" +
	"\tsignature\x18\x0e \x01(\fR\tsignatureB\t\n" +
	"\acontentJ\x04\b\x0f\x10\x15\"T\n" +
	"\vFindNodeReq\x12/\n" +
	"\vtarget_node\x18\x01 \x01(\v2\x0e.p2pmsg.NodeIDR\n" +
	"targetNode\x12\x14\n" +
	"\x05limit\x18\x02 \x01(\rR\x05limit\"_\n" +
	"\fNodeInfoResp\x12&\n" +
	"\x05nodes\x18\x01 \x03(\v2\x10.p2pmsg.NodeInfoR\x05nodes\x12'\n" +
	"\x05error\x18\x02 \x01(\v2\x11.p2pmsg.ErrorRespR\x05error\"\xb4\x01\n" +
	"\tFilePiece\x12\x17\n" +
	"\afile_id\x18\x01 \x01(\tR\x06fileId\x12\x1f\n" +
	"\vpiece_index\x18\x02 \x01(\rR\n" +
	"pieceIndex\x12!\n" +
	"\ftotal_pieces\x18\x03 \x01(\rR\vtotalPieces\x12\x12\n" +
	"\x04data\x18\x04 \x01(\fR\x04data\x12\x1d\n" +
	"\n" +
	"piece_hash\x18\x05 \x01(\fR\tpieceHash\x12\x17\n" +
	"\ais_last\x18\x06 \x01(\bR\x06isLast\"b\n" +
	"\x06ACKReq\x12\x15\n" +
	"\x06msg_id\x18\x01 \x01(\tR\x05msgId\x12\x18\n" +
	"\asuccess\x18\x02 \x01(\bR\asuccess\x12'\n" +
	"\x05error\x18\x03 \x01(\v2\x11.p2pmsg.ErrorRespR\x05error*\x85\x01\n" +
	"\aNatType\x12\x0f\n" +
	"\vNAT_UNKNOWN\x10\x00\x12\x17\n" +
	"\x13NAT_PORT_RESTRICTED\x10\x01\x12\x1a\n" +
	"\x16NAT_ADDRESS_RESTRICTED\x10\x02\x12\x11\n" +
	"\rNAT_FULL_CONE\x10\x03\x12\x11\n" +
	"\rNAT_SYMMETRIC\x10\x04\x12\x0e\n" +
	"\n" +
	"NAT_PUBLIC\x10\x05*l\n" +
	"\n" +
	"NodeStatus\x12\x17\n" +
	"\x13NODE_STATUS_UNKNOWN\x10\x00\x12\x16\n" +
	"\x12NODE_STATUS_ONLINE\x10\x01\x12\x14\n" +
	"\x10NODE_STATUS_BUSY\x10\x02\x12\x17\n" +
	"\x13NODE_STATUS_OFFLINE\x10\x03*\xb2\x01\n" +
	"\vMessageType\x12\x0f\n" +
	"\vMSG_UNKNOWN\x10\x00\x12\f\n" +
	"\bMSG_TEXT\x10\x01\x12\x11\n" +
	"\rMSG_HEARTBEAT\x10\x02\x12\f\n" +
	"\bMSG_JOIN\x10\x03\x12\r\n" +
	"\tMSG_LEAVE\x10\x04\x12\x11\n" +
	"\rMSG_FIND_NODE\x10\x05\x12\x11\n" +
	"\rMSG_NODE_INFO\x10\x06\x12\x12\n" +
	"\x0eMSG_FILE_PIECE\x10\a\x12\v\n" +
	"\aMSG_ACK\x10\b\x12\r\n" +
	"\tMSG_ERROR\x10\t*\x94\x01\n" +
	"\tErrorCode\x12\x0f\n" +
	"\vERR_SUCCESS\x10\x00\x12\x12\n" +
	"\x0eERR_NODE_EXIST\x10\x01\x12\x16\n" +
	"\x12ERR_NODE_NOT_FOUND\x10\x02\x12\x12\n" +
	"\x0eERR_NAT_FAILED\x10\x03\x12\x14\n" +
	"\x10ERR_SIGN_INVALID\x10\x04\x12\x0f\n" +
	"\vERR_NETWORK\x10\x05\x12\x0f\n" +
	"\vERR_VERSION\x10\x062\xdf\x02\n" +
	"\x0eP2PPeerService\x12)\n" +
	"\x04Join\x12\x0f.p2pmsg.JoinReq\x1a\x10.p2pmsg.JoinResp\x12:\n" +
	"\x0eNotifyNodeJoin\x12\x10.p2pmsg.NodeInfo\x1a\x16.google.protobuf.Empty\x12/\n" +
	"\x05Leave\x12\x0e.p2pmsg.NodeID\x1a\x16.google.protobuf.Empty\x12=\n" +
	"\rSendHeartbeat\x12\x14.p2pmsg.HeartbeatReq\x1a\x16.google.protobuf.Empty\x125\n" +
	"\bFindNode\x12\x13.p2pmsg.FindNodeReq\x1a\x14.p2pmsg.NodeInfoResp\x12?\n" +
	"\x11PeerMessageStream\x12\x12.p2pmsg.P2PMessage\x1a\x12.p2pmsg.P2PMessage(\x010\x01B\x10Z\x0e./proto/p2pmsgb\x06proto3"

var (
	file_proto_message_proto_rawDescOnce sync.Once
	file_proto_message_proto_rawDescData []byte
)

func file_proto_message_proto_rawDescGZIP() []byte {
	file_proto_message_proto_rawDescOnce.Do(func() {
		file_proto_message_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_message_proto_rawDesc), len(file_proto_message_proto_rawDesc)))
	})
	return file_proto_message_proto_rawDescData
}

var file_proto_message_proto_enumTypes = make([]protoimpl.EnumInfo, 4)
var file_proto_message_proto_msgTypes = make([]protoimpl.MessageInfo, 12)
var file_proto_message_proto_goTypes = []any{
	(NatType)(0),                // 0: p2pmsg.NatType
	(NodeStatus)(0),             // 1: p2pmsg.NodeStatus
	(MessageType)(0),            // 2: p2pmsg.MessageType
	(ErrorCode)(0),              // 3: p2pmsg.ErrorCode
	(*NodeID)(nil),              // 4: p2pmsg.NodeID
	(*NodeAddr)(nil),            // 5: p2pmsg.NodeAddr
	(*NodeInfo)(nil),            // 6: p2pmsg.NodeInfo
	(*ErrorResp)(nil),           // 7: p2pmsg.ErrorResp
	(*JoinReq)(nil),             // 8: p2pmsg.JoinReq
	(*JoinResp)(nil),            // 9: p2pmsg.JoinResp
	(*HeartbeatReq)(nil),        // 10: p2pmsg.HeartbeatReq
	(*P2PMessage)(nil),          // 11: p2pmsg.P2PMessage
	(*FindNodeReq)(nil),         // 12: p2pmsg.FindNodeReq
	(*NodeInfoResp)(nil),        // 13: p2pmsg.NodeInfoResp
	(*FilePiece)(nil),           // 14: p2pmsg.FilePiece
	(*ACKReq)(nil),              // 15: p2pmsg.ACKReq
	(*timestamp.Timestamp)(nil), // 16: google.protobuf.Timestamp
	(*empty.Empty)(nil),         // 17: google.protobuf.Empty
}
var file_proto_message_proto_depIdxs = []int32{
	0,  // 0: p2pmsg.NodeAddr.nat_type:type_name -> p2pmsg.NatType
	4,  // 1: p2pmsg.NodeInfo.id:type_name -> p2pmsg.NodeID
	5,  // 2: p2pmsg.NodeInfo.addrs:type_name -> p2pmsg.NodeAddr
	1,  // 3: p2pmsg.NodeInfo.status:type_name -> p2pmsg.NodeStatus
	16, // 4: p2pmsg.NodeInfo.last_active:type_name -> google.protobuf.Timestamp
	3,  // 5: p2pmsg.ErrorResp.code:type_name -> p2pmsg.ErrorCode
	6,  // 6: p2pmsg.JoinReq.node_info:type_name -> p2pmsg.NodeInfo
	7,  // 7: p2pmsg.JoinResp.error:type_name -> p2pmsg.ErrorResp
	6,  // 8: p2pmsg.JoinResp.peers:type_name -> p2pmsg.NodeInfo
	4,  // 9: p2pmsg.HeartbeatReq.node_id:type_name -> p2pmsg.NodeID
	1,  // 10: p2pmsg.HeartbeatReq.status:type_name -> p2pmsg.NodeStatus
	2,  // 11: p2pmsg.P2PMessage.type:type_name -> p2pmsg.MessageType
	4,  // 12: p2pmsg.P2PMessage.from:type_name -> p2pmsg.NodeID
	16, // 13: p2pmsg.P2PMessage.send_time:type_name -> google.protobuf.Timestamp
	10, // 14: p2pmsg.P2PMessage.heartbeat:type_name -> p2pmsg.HeartbeatReq
	12, // 15: p2pmsg.P2PMessage.find_node:type_name -> p2pmsg.FindNodeReq
	13, // 16: p2pmsg.P2PMessage.node_info:type_name -> p2pmsg.NodeInfoResp
	14, // 17: p2pmsg.P2PMessage.file_piece:type_name -> p2pmsg.FilePiece
	15, // 18: p2pmsg.P2PMessage.ack:type_name -> p2pmsg.ACKReq
	7,  // 19: p2pmsg.P2PMessage.error:type_name -> p2pmsg.ErrorResp
	4,  // 20: p2pmsg.FindNodeReq.target_node:type_name -> p2pmsg.NodeID
	6,  // 21: p2pmsg.NodeInfoResp.nodes:type_name -> p2pmsg.NodeInfo
	7,  // 22: p2pmsg.NodeInfoResp.error:type_name -> p2pmsg.ErrorResp
	7,  // 23: p2pmsg.ACKReq.error:type_name -> p2pmsg.ErrorResp
	8,  // 24: p2pmsg.P2PPeerService.Join:input_type -> p2pmsg.JoinReq
	6,  // 25: p2pmsg.P2PPeerService.NotifyNodeJoin:input_type -> p2pmsg.NodeInfo
	4,  // 26: p2pmsg.P2PPeerService.Leave:input_type -> p2pmsg.NodeID
	10, // 27: p2pmsg.P2PPeerService.SendHeartbeat:input_type -> p2pmsg.HeartbeatReq
	12, // 28: p2pmsg.P2PPeerService.FindNode:input_type -> p2pmsg.FindNodeReq
	11, // 29: p2pmsg.P2PPeerService.PeerMessageStream:input_type -> p2pmsg.P2PMessage
	9,  // 30: p2pmsg.P2PPeerService.Join:output_type -> p2pmsg.JoinResp
	17, // 31: p2pmsg.P2PPeerService.NotifyNodeJoin:output_type -> google.protobuf.Empty
	17, // 32: p2pmsg.P2PPeerService.Leave:output_type -> google.protobuf.Empty
	17, // 33: p2pmsg.P2PPeerService.SendHeartbeat:output_type -> google.protobuf.Empty
	13, // 34: p2pmsg.P2PPeerService.FindNode:output_type -> p2pmsg.NodeInfoResp
	11, // 35: p2pmsg.P2PPeerService.PeerMessageStream:output_type -> p2pmsg.P2PMessage
	30, // [30:36] is the sub-list for method output_type
	24, // [24:30] is the sub-list for method input_type
	24, // [24:24] is the sub-list for extension type_name
	24, // [24:24] is the sub-list for extension extendee
	0,  // [0:24] is the sub-list for field type_name
}

func init() { file_proto_message_proto_init() }
func file_proto_message_proto_init() {
	if File_proto_message_proto != nil {
		return
	}
	file_proto_message_proto_msgTypes[7].OneofWrappers = []any{
		(*P2PMessage_Text)(nil),
		(*P2PMessage_Heartbeat)(nil),
		(*P2PMessage_FindNode)(nil),
		(*P2PMessage_NodeInfo)(nil),
		(*P2PMessage_FilePiece)(nil),
		(*P2PMessage_Ack)(nil),
		(*P2PMessage_Error)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_message_proto_rawDesc), len(file_proto_message_proto_rawDesc)),
			NumEnums:      4,
			NumMessages:   12,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_message_proto_goTypes,
		DependencyIndexes: file_proto_message_proto_depIdxs,
		EnumInfos:         file_proto_message_proto_enumTypes,
		MessageInfos:      file_proto_message_proto_msgTypes,
	}.Build()
	File_proto_message_proto = out.File
	file_proto_message_proto_goTypes = nil
	file_proto_message_proto_depIdxs = nil
}
